### PR TITLE
Fix severity graph [fixes #14]

### LINKED ISSUE #14: Fix severity graph
screen shot 2016-11-19 at 13 07 09

The problem is that it is not clear what severity level is shown

### PR DESCRIPTION
**Pull request by sseliverstov**

### CODE REVIEW

**Comment by sseliverstov** [comment]
@baev

File: face/src/plugins/graph/charts/SeverityChart.js [hunk 1]
```diff
@@ -56,6 +56,9 @@ export default class SeverityChart extends BaseChartView {
             left: PAD_LEFT
         });
 
+        this.svg.selectAll('.tick').select('line')
+            .attr('transform','translate('+ (this.x.step()/2) +',0)');
```
Comment (baev) [inline face/src/plugins/graph/charts/SeverityChart.js]: indents
